% compare bayes factor estimates

clear; close all;

%% constants
dataName = 'MistryLiljeholmExp1';
fontSize = 14;
try load pantoneSpring2015 pantone; catch load PantoneSpring2015 pantone; end
doPrint = true;

%% load estimates
load sdBF sdBF
load psBF psBF

figure(1); clf; hold on;
set(gcf, ...
   'color'             , 'w'               , ...
   'units'             , 'normalized'      , ...
   'position'          , [0.2 0.2 0.4 0.6] , ...
   'paperpositionmode' , 'auto'            );

set(gca, ...
   'units'         , 'normalized'      , ...
   'position'      , [0.1 0.1 0.8 0.8] , ...
   'xlim'          , [-10 10]          , ...
   'xtick'         , -10:2:10          , ...
   'ylim'          , [-10 10]          , ...
   'ytick'         , -10:2:10          , ...
   'box'           , 'on'              , ...
   'tickdir'       , 'out'             , ...
   'layer'         , 'top'             , ...
   'ticklength'    , [0.01 0]          , ...
   'fontsize'      , fontSize          );
axis square;
xlabel('Savage-Dickey log BF', 'fontsize', fontSize+2);
ylabel('Product-Space log BF', 'fontsize', fontSize+2);

plot([-10 10], [-10 10], '-', ...
   'color', pantone.Titanium);
plot(log(sdBF), log(psBF), 'o', ...
   'markersize'      , 8                   , ...
   'markerfacecolor' , pantone.ClassicBlue , ...
   'markeredgecolor' , 'w'                 );

   % print
   if doPrint
      print(sprintf('figures/%s%s.png', dataName, 'BFcomparison'), '-dpng', '-r300');
      print(sprintf('figures/%s%s.eps', dataName, 'BFcomparison'), '-depsc');
   end
