%% consensus_2
% one w and tau parameter for all subjects
% uses PantoneSpring2015.mat; subplotArrange.m

clear; close all;

%% constants
dataName = 'MistryLiljeholmExp1';
credibleInterval = 95;
fontSize = 14;
wStep = 0.02;
doPrint = true;

%% derived constants
wBinsC = wStep/2:wStep:(1-wStep/2);
wBinsE = 0:wStep:1;

%% load data (originally parsed in consensus_1) and graphics support
load(dataName, 'd');
try load pantoneSpring2015 pantone; catch load PantoneSpring2015 pantone; end

%% graphical model
modelName = 'consensus_2';

% parameters to monitor
params = {'w', 'tau'};

% generator for initialization% MCMC properties
% nChains = 4; nBurnin = 1e4; nSamples = 5e3; nThin = 100;  doParallel = 1;
% nChains = 6; nBurnin = 5e3; nSamples = 1e3; nThin = 100; doParallel = 1;
% nChains = 6; nBurnin = 5e3; nSamples = 2e3; nThin = 10; doParallel = 1;
nChains = 8; nBurnin = 1e3; nSamples = 1e4; nThin = 1;  doParallel = 1;
% nChains = 1; nBurnin = 0; nSamples = 100; nThin = 1;  doParallel = 0;

engine = 'jags';

generator = @()struct('w', rand(d.nSubjects, 1), 'tau', ones(d.nSubjects, 1));

% input for graphical model
data = struct(...
   'y'          , 2-d.decision      , ... % transform to Bernoulli 1 for majority and 0 for minority
   'nSubjects'  , d.nSubjects       , ... ...
   'nTrials'    , d.nTrials         , ...
   'm'          , d.values          , ...
   'c'          , d.majority        );

fileName = sprintf('storage/%s_%s', modelName, dataName);
if exist([fileName '.mat'], 'file')
   load(fileName, 'stats', 'chains', 'diagnostics', 'info');
else
   tic; % start clock
   [stats, chains, diagnostics, info] = callbayes(engine, ...
      'model'           ,  [modelName '.txt']                        , ...
      'data'            ,  data                                      , ...
      'outputname'      ,  'samples'                                 , ...
      'init'            ,  generator                                 , ...
      'datafilename'    ,  modelName                                 , ...
      'initfilename'    ,  modelName                                 , ...
      'scriptfilename'  ,  modelName                                 , ...
      'logfilename'     ,  modelName                                 , ...
      'nchains'         ,  nChains                                   , ...
      'nburnin'         ,  nBurnin                                   , ...
      'nsamples'        ,  nSamples                                  , ...
      'monitorparams'   ,  params                                    , ...
      'thin'            ,  nThin                                     , ...
      'workingdir'      ,  ['tmp/' modelName]                        , ...
      'verbosity'       ,  0                                         , ...
      'saveoutput'      ,  true                                      , ...
      'allowunderscores',  1                                         , ...
      'parallel'        ,  doParallel                                , ...
      'modules'         ,  {'dic'}                                   );
   fprintf('%s took %f seconds!\n', upper(engine), toc); % show timing
   save(fileName, 'stats', 'chains', 'diagnostics', 'info');
end

%% results

% convergence and summary
disp('Convergence statistics:')
grtable(chains, 1.05)

codatable(chains);

mnW = codatable(chains, 'w', @mean);
mnTau = codatable(chains, 'tau', @mean);
ciW = nan(d.nSubjects, 2);
ciTau = nan(d.nSubjects, 2);
for idx = 1:d.nSubjects
   ciW(idx, :) = prctile(chains.(sprintf('w_%d', idx))(:), [(100-credibleInterval)/2 100-(100-credibleInterval)/2]);
   ciTau(idx, :) = prctile(chains.(sprintf('tau_%d', idx))(:), [(100-credibleInterval)/2 100-(100-credibleInterval)/2]);
end

% scatter
figure(1); clf; hold on;
set(gcf, ...
   'color'             , 'w'               , ...
   'units'             , 'normalized'      , ...
   'position'          , [0.2 0.2 0.45 0.6] , ...
   'paperpositionmode' , 'auto'            );

set(gca, ...
   'units'         , 'normalized'      , ...
   'position'      , [0.1 0.1 0.8 0.8] , ...
   'xlim'          , [0 1]             , ...
   'xtick'         , 0:0.2:1           , ...
   'ylim'          , [0 max(ciTau(:))] , ...
   'ytick'         , 0:1:max(ciTau(:)) , ...
   'box'           , 'off'             , ...
   'tickdir'       , 'out'             , ...
   'layer'         , 'top'             , ...
   'ticklength'    , [0.01 0]          , ...
   'fontsize'      , fontSize          );
xlabel('w', 'fontsize', fontSize+2);
ylabel('tau', 'fontsize', fontSize+2);

for idx = 1:d.nSubjects
   plot(ones(1, 2)*mnW(idx), ciTau(idx, :), '-', 'color', pantone.GlacierGray);
   plot(ciW(idx, :), ones(1, 2)*mnTau(idx), '-', 'color', pantone.GlacierGray);
end

for idx = 1:d.nSubjects
   plot(mnW(idx), mnTau(idx), 'o', ...
      'markersize'      , 8                   , ...
      'markerfacecolor' , pantone.DuskBlue    , ...
      'markeredgecolor' , 'w'                 );
   text(mnW(idx), mnTau(idx), sprintf('%d', idx), ...
      'fontsize'   , fontSize-2 , ...
      'horizontal' , 'left'     , ...
      'vertical'   , 'bottom'   , ...
      'layer'      , 'front'    );
end

% print
if doPrint
   print(sprintf('figures/%s%s%s.png', dataName, modelName, 'Scatter'), '-dpng', '-r300');
   print(sprintf('figures/%s%s%s.eps', dataName, modelName, 'Scatter'), '-depsc');
end


% savage dickey BF for w=0 vs w ~ dunif(0, 1)
figure(2); clf; hold on;
set(gcf, ...
   'color'             , 'w'               , ...
   'units'             , 'normalized'      , ...
   'position'          , [0.2 0.2 0.5 0.6] , ...
   'paperpositionmode' , 'auto'            );

[nRows, nCols] = subplotArrange(d.nSubjects);
[~, sortIdx] = sort(ciW(:, 1), 'ascend');
sdBF = nan(d.nSubjects, 1); % savage-dickey BF

for idx = 1:d.nSubjects
   count = histc(chains.(sprintf('w_%d', sortIdx(idx)))(:), wBinsE);
   count = count(1:end-1);
   count = count/sum(count)/wStep;
   sdBF(sortIdx(idx)) = count(1)/sum(count)/wStep;
   
   subplot(nRows, nCols, idx); hold on;
   set(gca, ...
      'xlim'          , [0 1]             , ...
      'xtick'         , 0:0.2:1           , ...
      'xticklabel'    , {'0', '', '', '', '', '1'}, ...
      'ycolor'        , 'none'            , ...
      'box'           , 'off'             , ...
      'tickdir'       , 'out'             , ...
      'layer'         , 'top'             , ...
      'ticklength'    , [0.1 0]          , ...
      'fontsize'      , fontSize-2          );
   xlabel(sprintf('s%d', sortIdx(idx)), ...
      'fontsize' , fontSize , ...
      'vertical' , 'bot'    );
   
   bar(wBinsC, count, 1, ...
      'facecolor' , pantone.DuskBlue , ...
      'edgecolor' , 'none'           );
   plot([0 1], [1 1], 'k-'); % prior density
   
   text(0, max(get(gca, 'ylim')), sprintf('BF = %1.1f', sdBF(sortIdx(idx))), ...
      'fontsize' , fontSize-2 , ...
      'vert'     , 'top'      );
   
end

save sdBF sdBF

% print
if doPrint
   print(sprintf('figures/%s%s%s.png', dataName, modelName, 'SavageDickey'), '-dpng', '-r300');
   print(sprintf('figures/%s%s%s.eps', dataName, modelName, 'SavageDickey'), '-depsc');
end

